apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-a-staging

resources:
- deployment.yaml

commonLabels:
  app.kubernetes.io/name: ai-service
  app.kubernetes.io/part-of: madriam-platform
